server:
  port: 8000

spring:
  application:
    name: oauth2-server

logging:
  level:
    ROOT: INFO
    http.wire-log: DEBUG

logbook:
  format:
    style: http
  obfuscate:
    parameters:
      - access_token
      - refresh_token
      - password
  write:
    level: DEBUG
    category: http.wire-log

security:
  user:
    password: mysecretpassword
---
spring:
   profiles: test
