server:
  port: 8000

spring:
  application:
    name: oauth2-server

logging:
  level:
    ROOT: INFO
    http.wire-log: DEBUG

logbook:
  format:
    style: http
  obfuscate:
    parameters:
      - access_token
      - refresh_token
      - password
  write:
    level: DEBUG
    category: http.wire-log
---
spring:
  profiles: mongo
  data:
    mongodb:
      host: localhost
      port: 27017
      database: oauth2
logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG
---
spring:
   profiles: test
